clear all
clc
format long


filename = 'C:\Users\Annie RingvallMoberg\Annie\PhD\GU\GUNILLA\Cs\Data\Cs_EA.txt';
hc=1239.84193; %eV*nm

%dataTable=readtable(filename,'ReadVariableNames',false);
[Run, WLRednm, LaserPowerRedmW, LaserPowerGreenmW, IonCurrentpA, stdDev1, Signal1, Signal2, Signal3, AverageSignal, Total1, Total2, Total3, AverageTotal, Background, Note] = importfile(filename, [2,15]);%energy = dataTable.Var1;  %WL in nm
%signal = dataTable.Var2; %Average signal
%error = dataTable.Var3; %Background

energy=hc./WLRednm;
%%outliers=excludedata(energy,signal,'indices',[28,29]); 
normData= AverageTotal./(LaserPowerRedmW.*IonCurrentpA);
%normData= AverageSignal
%plot(WLRednm,normData,'o')

%%%%Calculating the Weigthed Average%%%%
time=300; %s

Signal=(Signal1+Signal2+Signal3);
Signal_norm=Signal./(LaserPowerRedmW.*IonCurrentpA);

g=sqrt(Signal_norm)./time;  %Poission uncertanty 
%g_5=sqrt(Signal5)./time;
%g_6=sqrt(Signal6)./time;
% 
% Signal_norm_4=Signal4./(LaserPowerRedmW.*IonCurrentpA); %
% Signal_norm_5=Signal5./(LaserPowerRedmW.*IonCurrentpA);
% Signal_norm_6=Signal6./(LaserPowerRedmW.*IonCurrentpA);
% 
% g_norm_4=g_4./(LaserPowerRedmW.*IonCurrentpA);
% g_norm_5=g_5./(LaserPowerRedmW.*IonCurrentpA);
% g_norm_6=g_6./(LaserPowerRedmW.*IonCurrentpA);
% 
% G_4=g_norm_4.*Signal_norm_4;
% G_5=g_norm_5.*Signal_norm_5;
% G_6=g_norm_6.*Signal_norm_6;
% 
% 
% SumG=G_4+G_5+G_6;
% Sumg=g_4+g_5+g_6;
% 
% G_Avg=SumG./Sumg; %weigthed average
% 
% error=(sqrt(Sumg)).^(-1); %sigma

hold on
e=errorbar(WLRednm, Signal_norm, g,'.');
%s = e.LineStyle;
%e.Color = '[0.5,0.5,0.7]';
%e.MarkerSize = 3;

startPoint = [0.5, 30, 1.92683];
%fitting = fittype(@(A ,B ,E_0 , x) A + B*sqrt(x - E_0 + abs(x - E_0)));
fitting = fittype('A + B*sqrt(x - E_0 + abs(x - E_0)(A ,B ,E_0 , x))');

myfit = fit(energy, Signal_norm, fitting, 'StartPoint', startPoint,'Weight', 1./g.^2);

% myfit = fit(WLRednm, Signal_norm, fitting);
% EA_values = coeffvalues(myfit);
% EA = EA_values(3);
% values = confint(myfit,0.95)
% error = abs(values(1,3)-values(2,3))/2;
% SP1 = values(1,3);
% SP2 = values(2,3);
% 
% set(findall(gcf,'-property','FontSize'),'FontSize',15)
% x0=10;
% y0=10;
% width=800;
% height=400;
% hold on
% plot(myfit,'k')
% set(gcf,'position',[x0,y0,width,height])
% xlim([WLRednm(1)+0.00001 WLRednm(length(WLRednm))+0.000005])
% xlabel('Photon Energy (eV)')
% ylabel('n_i/(n_{total}-n_i)')
% line([SP1 SP1], get(gca, 'ylim'), 'Color',[0.7,0.5,0.5]);
% line([SP2 SP2], get(gca, 'ylim'), 'Color',[0.7,0.5,0.5]);
% % SP=1.92683; %your point goes here 
% % line([SP SP],get(axes,'YLim'),'Color',[1 0 0])
% % xt={'1.92678' ; '1.92680' ; '1.92682' ; '1.92684' ; '1.92686'; '1.92688'} ; 
% % set(gcf,'xtick',1:6); 
% % set(gcf,'xticklabel',xt);
% 
% box on
% fig = gcf;
% fig.PaperPositionMode = 'auto';
% fig_pos = fig.PaperPosition;
% fig.PaperSize = [fig_pos(3) fig_pos(4)];
% legend('Data','Wigner fit')

fprintf('Done')
%% functions 
function [Run, WLRednm, LaserPowerRedmW, LaserPowerGreenmW, IonCurrent1pA, stdDev1, Signal1, Total1, IonCurrent2pA, stdDev2, Signal2, Total2, IonCurrent3pA, stdDev3, Signal3, Total3, VarName17, AverageSignal, AverageTotal, Background, Note] = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  [RUN, WLREDNM, LASERPOWERREDMW, LASERPOWERGREENMW, IONCURRENT1PA,
%  STDDEV1, SIGNAL1, TOTAL1, IONCURRENT2PA, STDDEV2, SIGNAL2, TOTAL2,
%  IONCURRENT3PA, STDDEV3, SIGNAL3, TOTAL3, VARNAME17, AVERAGESIGNAL,
%  AVERAGETOTAL, BACKGROUND, NOTE] = IMPORTFILE1(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as column vectors.
%
%  [RUN, WLREDNM, LASERPOWERREDMW, LASERPOWERGREENMW, IONCURRENT1PA,
%  STDDEV1, SIGNAL1, TOTAL1, IONCURRENT2PA, STDDEV2, SIGNAL2, TOTAL2,
%  IONCURRENT3PA, STDDEV3, SIGNAL3, TOTAL3, VARNAME17, AVERAGESIGNAL,
%  AVERAGETOTAL, BACKGROUND, NOTE] = IMPORTFILE1(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Run, WLRednm, LaserPowerRedmW, LaserPowerGreenmW, IonCurrent1pA, stdDev1, Signal1, Total1, IonCurrent2pA, stdDev2, Signal2, Total2, IonCurrent3pA, stdDev3, Signal3, Total3, VarName17, AverageSignal, AverageTotal, Background, Note] = importfile1("C:\Users\Annie RingvallMoberg\Annie\PhD\GU\GUNILLA\Cs\Data\Cs_EA.txt", [2, 15]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Feb-2021 21:28:01

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Run", "WLRednm", "LaserPowerRedmW", "LaserPowerGreenmW", "IonCurrent1pA", "stdDev1", "Signal1", "Total1", "IonCurrent2pA", "stdDev2", "Signal2", "Total2", "IonCurrent3pA", "stdDev3", "Signal3", "Total3", "VarName17", "AverageSignal", "AverageTotal", "Background", "Note"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName17", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName17", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Note", "TrimNonNumeric", true);
opts = setvaropts(opts, "Note", "ThousandsSeparator", ",");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Run = tbl.Run;
WLRednm = tbl.WLRednm;
LaserPowerRedmW = tbl.LaserPowerRedmW;
LaserPowerGreenmW = tbl.LaserPowerGreenmW;
IonCurrent1pA = tbl.IonCurrent1pA;
stdDev1 = tbl.stdDev1;
Signal1 = tbl.Signal1;
Total1 = tbl.Total1;
IonCurrent2pA = tbl.IonCurrent2pA;
stdDev2 = tbl.stdDev2;
Signal2 = tbl.Signal2;
Total2 = tbl.Total2;
IonCurrent3pA = tbl.IonCurrent3pA;
stdDev3 = tbl.stdDev3;
Signal3 = tbl.Signal3;
Total3 = tbl.Total3;
VarName17 = tbl.VarName17;
AverageSignal = tbl.AverageSignal;
AverageTotal = tbl.AverageTotal;
Background = tbl.Background;
Note = tbl.Note;
end